# Docker Compose for Archer Fitness
# This configuration pulls the image from DockerHub and runs it in production
# Database is hosted externally, so it's not included here

services:
  archer-fitness:
    image: ad-archer/archer-fitness:latest
    container_name: archer-fitness
    network_mode: host
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
    restart: unless-stopped
    # Health check using the configured port
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-3000}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Security: Drop all capabilities and run as non-root
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    # Only mount necessary volumes
    volumes:
      - /tmp:/tmp:ro
