services:
  app:
    container_name: archer-fitness
    build: .
    ports:
      - "3676:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:3676
    restart: unless-stopped
    # Remove volumes for production - everything should be in the container
    # volumes:
    #   - .:/app
    #   - /app/node_modules

#   # Database service
#   db:
#     image: postgres:15-alpine
#     container_name: archer-fitness-db
#     environment:
#       - POSTGRES_USER=archer_fitness_user
#       - POSTGRES_PASSWORD=changeme
#       - POSTGRES_DB=archer_fitness
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
