"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "@/components/ui/carousel"
import Link from "next/link"
import Image from "next/image"
import { ArrowRight, Target, TrendingUp, Utensils, Calendar, BarChart3, Dumbbell, X } from "lucide-react"
import { useEffect, useState } from "react"

export function WelcomeScreen() {
  const [lightboxOpen, setLightboxOpen] = useState(false)
  const [selectedImage, setSelectedImage] = useState<string | null>(null)
  const [isDesktop, setIsDesktop] = useState(false)

  useEffect(() => {
    const mq = window.matchMedia('(min-width: 1024px)') // lg breakpoint
    const update = () => setIsDesktop(mq.matches)
    update()
    mq.addEventListener('change', update)
    return () => mq.removeEventListener('change', update)
  }, [])
  const features = [
    {
      icon: Dumbbell,
      title: "AI Workout Generation",
      description: "Get personalized workouts generated by AI based on your goals, fitness level, and available equipment.",
      image: "/screens/exercise.png"
    },
    {
      icon: Utensils,
      title: "Smart Nutrition",
      description: "AI-calculated nutrition goals and meal suggestions tailored to your fitness objectives.",
      image: "/screens/nutrition-tracker.png"
    },
    {
      icon: BarChart3,
      title: "Progress Analytics",
      description: "Track your workouts, nutrition, and progress with detailed analytics and insights.",
      image: "/screens/progress-analytics.png"
    },
    {
      icon: Calendar,
      title: "Schedule Manager",
      description: "Plan and organize your workout schedule with smart reminders and progress tracking.",
      image: "/screens/schedule-manager.png"
    },
    {
      icon: TrendingUp,
      title: "Weight Progress",
      description: "Monitor your weight changes and body composition with visual progress charts.",
      image: "/screens/weightprogress.png"
    },
    {
      icon: Target,
      title: "Workout History",
      description: "Keep track of all your completed workouts and performance metrics over time.",
      image: "/screens/workout-history.png"
    }
  ]

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-[#ff5555]/10 to-[#ff5555]/20 dark:from-slate-950 dark:via-[#ff5555]/10 dark:to-[#ff5555]/20">
      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-r from-[#ff5555]/20 to-[#ff5555]/10" />
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-16">
          <div className="text-center">
            <div className="mb-10 max-w-4xl mx-auto">
              <div className="relative overflow-hidden rounded-2xl shadow-2xl ring-1 ring-[#ff5555]/30">
                <Image
                  src="/sitebanner.webp"
                  alt="Archer Fitness Banner"
                  width={1280}
                  height={420}
                  className="w-full h-auto object-cover"
                  priority
                />
              </div>
            </div>
            <h1 className="text-5xl md:text-7xl font-bold text-[#ff5555] mb-6">
              Archer Fitness
            </h1>
            <p className="text-xl md:text-2xl text-muted-foreground mb-8 max-w-3xl mx-auto leading-relaxed">
              AI-powered workout planning and progress tracking designed to help you reach your fitness goals faster than ever.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center mb-12">
              <Button asChild size="lg" className="bg-[#ff5555] hover:bg-[#e04444] text-white px-8 py-4 text-lg font-semibold shadow-lg hover:shadow-xl transition-all duration-300">
                <Link href="/auth/signin" className="flex items-center gap-2">
                  Get Started
                  <ArrowRight className="w-5 h-5" />
                </Link>
              </Button>
              <Button asChild variant="outline" size="lg" className="px-8 py-4 text-lg font-semibold border-2 border-[#ff5555] text-[#ff5555] hover:bg-[#ff5555]/10 dark:hover:bg-[#ff5555]/20 transition-all duration-300">
                <Link href="/auth/signup">Create Account</Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Features Carousel */}
      <section className="py-16 bg-white/50 dark:bg-slate-900/50 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-slate-900 dark:text-slate-100 mb-4">
              Powerful Features at Your Fingertips
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Discover how Archer Fitness can transform your fitness journey with cutting-edge AI technology
            </p>
          </div>

          <Carousel className="w-full max-w-6xl mx-auto">
            <CarouselContent>
              {features.map((feature, index) => (
                <CarouselItem key={index} className="md:basis-2/3 lg:basis-1/2 xl:basis-1/3">
                  <Card className="h-full border border-[#ff5555]/20 shadow-lg hover:shadow-2xl transition-all duration-300 bg-white/90 dark:bg-slate-800/90 backdrop-blur">
                    <CardHeader className="text-center pb-2 pt-6">
                      <div className="w-20 h-20 mx-auto mb-4 bg-[#ff5555] rounded-full flex items-center justify-center">
                        <feature.icon className="w-10 h-10 text-white" />
                      </div>
                      <CardTitle className="text-2xl font-semibold">{feature.title}</CardTitle>
                    </CardHeader>
                    <CardContent className="text-center">
                      <p className="text-muted-foreground mb-6 leading-relaxed text-base md:text-lg">
                        {feature.description}
                      </p>
                      <div 
                        className="relative w-full h-60 md:h-64 rounded-xl overflow-hidden shadow-lg cursor-pointer lg:cursor-zoom-in group"
                        onClick={() => {
                          if (isDesktop) {
                            setSelectedImage(feature.image)
                            setLightboxOpen(true)
                          }
                        }}
                        role="button"
                        tabIndex={0}
                        onKeyDown={(e) => {
                          if (isDesktop && (e.key === 'Enter' || e.key === ' ')) {
                            e.preventDefault()
                            setSelectedImage(feature.image)
                            setLightboxOpen(true)
                          }
                        }}
                        aria-label={`Open ${feature.title} image in lightbox`}
                      >
                        <Image
                          src={feature.image}
                          alt={feature.title}
                          fill
                          className="object-cover hover:scale-105 transition-transform duration-300 lg:group-hover:scale-[1.02]"
                        />
                      </div>
                    </CardContent>
                  </Card>
                </CarouselItem>
              ))}
            </CarouselContent>
            <CarouselPrevious className="left-4" />
            <CarouselNext className="right-4" />
          </Carousel>
        </div>
      </section>

      {/* Desktop-only Lightbox for Features */}
      {lightboxOpen && isDesktop && selectedImage && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm"
          onClick={() => setLightboxOpen(false)}
          aria-modal="true"
          role="dialog"
        >
          <button
            aria-label="Close lightbox"
            className="absolute top-6 right-6 rounded-full p-2 bg-white/10 hover:bg-white/20 text-white"
            onClick={() => setLightboxOpen(false)}
          >
            <X className="h-6 w-6" />
          </button>
          <div className="relative w-[90vw] max-w-6xl h-[70vh]" onClick={(e) => e.stopPropagation()}>
            <Image
              src={selectedImage}
              alt="Feature enlarged"
              fill
              className="object-contain"
              priority
            />
          </div>
        </div>
      )}

      {/* Stats Section */}
      <section className="py-16 bg-[#ff5555] text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid md:grid-cols-3 gap-8 text-center">
            <div className="space-y-2">
              <div className="text-4xl font-bold">AI-Powered</div>
              <div className="text-red-100">Personalized Workouts</div>
            </div>
            <div className="space-y-2">
              <div className="text-4xl font-bold">Real-Time</div>
              <div className="text-red-100">Progress Tracking</div>
            </div>
            <div className="space-y-2">
              <div className="text-4xl font-bold">Smart</div>
              <div className="text-red-100">Nutrition Planning</div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 bg-slate-900 text-white">
        <div className="max-w-4xl mx-auto text-center px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl md:text-4xl font-bold mb-6">
            Ready to Transform Your Fitness Journey?
          </h2>
          <p className="text-xl text-slate-300 mb-8 max-w-2xl mx-auto">
            Join thousands of users who have achieved their fitness goals with Archer Fitness.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button asChild size="lg" className="bg-[#ff5555] hover:bg-[#e04444] text-white px-8 py-4 text-lg font-semibold">
              <Link href="/auth/signin" className="flex items-center gap-2">
                Start Your Journey
                <ArrowRight className="w-5 h-5" />
              </Link>
            </Button>
          </div>
        </div>
      </section>
    </div>
  )
}
