import {
  Flame,
  Sparkles,
  Mountain,
  TrendingUp,
  Dumbbell,
  Shield,
  Zap,
  Crown,
  Footprints,
  Activity,
  Target,
  Trophy,
} from "lucide-react"
import type { ProgressionBranch } from "./types"

export const progressionBranches: ProgressionBranch[] = [
  {
    id: "push-tree",
    title: "Push Power Tree",
    subtitle: "Guide your pressing strength toward a strict one-arm push-up",
    icon: Flame,
    accent: "from-orange-500/10 via-rose-500/5 to-red-500/10",
    description: "Stack pressing XP and climb toward one-arm push-ups.",
    milestones: [
      {
        id: "push-foundation",
        name: "Incline Push Foundations",
        tier: 0,
        xp: 60,
        badgeIcon: TrendingUp,
        focus: "Joint prep",
        description: "Scap drills + incline reps to lock clean mechanics.",
        reward: "Unlock diamond tempo drills",
        targetSessions: 2,
        prerequisites: [],
        exerciseKeywords: ["incline push-up"],
        template: {
          slug: "tree-incline-push",
          name: "Tree • Incline Push Foundations",
          description: "Groove tight push-up form with scapular prep and incline tempo work.",
          category: "Push",
          difficulty: "beginner",
          estimatedDuration: 28,
          focus: "Volume",
          exercises: [
            { name: "Scapular Push-Up", targetSets: 3, targetReps: "12-15" },
            { name: "Incline Push-Up", targetSets: 4, targetReps: "10-14" },
            { name: "Tempo Push-Up (3-1-1)", targetSets: 3, targetReps: "8-10" },
          ],
        },
      },
      {
        id: "push-volume",
        name: "Classic Push Mastery",
        tier: 1,
        xp: 90,
        badgeIcon: Dumbbell,
        focus: "Mid-range power",
        description: "High-volume push-ups and tricep finishers for elbow armor.",
        reward: "Unlock lean + explosive nodes",
        targetSessions: 3,
        prerequisites: ["push-foundation"],
        exerciseKeywords: ["push-up", "diamond push-up"],
        template: {
          slug: "tree-classic-push",
          name: "Tree • Push Volume Builder",
          description: "Classic push variations with tricep finishers to build dense pressing volume.",
          category: "Push",
          difficulty: "beginner",
          estimatedDuration: 32,
          focus: "Hypertrophy",
          exercises: [
            { name: "Standard Push-Up", targetSets: 4, targetReps: "12-15" },
            { name: "Diamond Push-Up", targetSets: 3, targetReps: "8-12" },
            { name: "Decline Push-Up", targetSets: 3, targetReps: "8-10" },
            { name: "Bench Dips", targetSets: 3, targetReps: "12-15" },
          ],
        },
      },
      {
        id: "push-pseudo-planche",
        name: "Pseudo Planche Lean",
        tier: 2,
        xp: 120,
        badgeIcon: Shield,
        focus: "Leverage strength",
        description: "Forward leans and hollow holds overload shoulders.",
        reward: "Unlock one-arm negative quests",
        targetSessions: 3,
        prerequisites: ["push-volume"],
        exerciseKeywords: ["pseudo planche"],
        template: {
          slug: "tree-pseudo-planche",
          name: "Tree • Pseudo Planche Builder",
          description: "Hollow body prep, lean holds, and deep deficit push work to overload shoulders.",
          category: "Push",
          difficulty: "intermediate",
          estimatedDuration: 35,
          focus: "Strength",
          exercises: [
            { name: "Hollow Body Hold", targetSets: 3, targetReps: "40s", targetType: "time" },
            { name: "Pseudo Planche Lean", targetSets: 5, targetReps: "20s", targetType: "time" },
            { name: "Deficit Push-Up", targetSets: 4, targetReps: "6-8" },
            { name: "Ring Archer Push-Up", targetSets: 3, targetReps: "6-8" },
          ],
        },
      },
      {
        id: "push-unilateral-negatives",
        name: "One-Arm Negatives",
        tier: 3,
        xp: 150,
        badgeIcon: Zap,
        focus: "Unilateral control",
        description: "Tempo drops + offsets dial in single-arm control.",
        reward: "Unlock one-arm attempts",
        targetSessions: 4,
        prerequisites: ["push-pseudo-planche"],
        exerciseKeywords: ["one arm push", "oa push", "archer push"],
        template: {
          slug: "tree-one-arm-negatives",
          name: "Tree • One-Arm Push Negatives",
          description: "Isometric offsets and tempo eccentrics for confident unilateral pressing.",
          category: "Push",
          difficulty: "intermediate",
          estimatedDuration: 38,
          focus: "Control",
          exercises: [
            { name: "Archer Push-Up", targetSets: 4, targetReps: "6-8" },
            { name: "One-Arm Push-Up Negative", targetSets: 5, targetReps: "3-5" },
            { name: "One-Arm Incline Push-Up", targetSets: 4, targetReps: "6-10" },
            { name: "Ring Support Hold", targetSets: 3, targetReps: "40s", targetType: "time" },
          ],
        },
      },
      {
        id: "push-one-arm",
        name: "True One-Arm Push-Up",
        tier: 4,
        xp: 200,
        badgeIcon: Crown,
        focus: "Skill expression",
        description: "Express full one-arm push power with low-rep singles.",
        reward: "Unlock weighted + showcase runs",
        targetSessions: 4,
        prerequisites: ["push-unilateral-negatives"],
        exerciseKeywords: ["one arm push-up", "one-arm push-up"],
        template: {
          slug: "tree-one-arm-push",
          name: "Tree • One-Arm Push Showcase",
          description: "Primers plus low-rep singles to maintain crisp one-arm push strength.",
          category: "Push",
          difficulty: "advanced",
          estimatedDuration: 34,
          focus: "Skill",
          exercises: [
            { name: "Pseudo Planche Lean", targetSets: 3, targetReps: "20s", targetType: "time" },
            { name: "One-Arm Push-Up", targetSets: 6, targetReps: "2-4" },
            { name: "Explosive Archer Push-Up", targetSets: 4, targetReps: "4-6" },
            { name: "Weighted Push-Up", targetSets: 4, targetReps: "5-7" },
          ],
        },
      },
    ],
  },
  {
    id: "inversion-tree",
    title: "Inversion Skill Tree",
    subtitle: "Climb toward one-arm handstands and archer handstand push-ups",
    icon: Sparkles,
    accent: "from-blue-500/10 via-cyan-500/5 to-indigo-500/10",
    description: "Level up inversions until handstand push-ups feel like a flex.",
    milestones: [
      {
        id: "invert-frogs",
        name: "Crow & Frog Holds",
        tier: 0,
        xp: 60,
        badgeIcon: Footprints,
        focus: "Balance foundation",
        description: "Crow + frog holds teach wrist loading and basic balance.",
        reward: "Unlock headstand prep node",
        targetSessions: 2,
        prerequisites: [],
        exerciseKeywords: ["crow pose", "frog stand"],
        template: {
          slug: "tree-frog-stands",
          name: "Tree • Frog Stand Lab",
          description: "Low-level inversions that teach wrist loading and balance corrections.",
          category: "Inversion",
          difficulty: "beginner",
          estimatedDuration: 25,
          focus: "Balance",
          exercises: [
            { name: "Wrist Prep Flow", targetSets: 3, targetReps: "60s", targetType: "time" },
            { name: "Crow Pose Hold", targetSets: 4, targetReps: "20-30s", targetType: "time" },
            { name: "Frog Stand Shifts", targetSets: 4, targetReps: "12 reps" },
          ],
        },
      },
      {
        id: "invert-headstand",
        name: "Headstand Push Prep",
        tier: 1,
        xp: 90,
        badgeIcon: Activity,
        focus: "Neck friendly strength",
        description: "Wall walks + headstand presses toughen shoulders.",
        reward: "Unlock freestanding drills",
        targetSessions: 3,
        prerequisites: ["invert-frogs"],
        exerciseKeywords: ["headstand push", "wall walk"],
        template: {
          slug: "tree-headstand-push",
          name: "Tree • Headstand Push Prep",
          description: "Slow negatives, wall walks, and pike presses for fearless inversions.",
          category: "Inversion",
          difficulty: "beginner",
          estimatedDuration: 33,
          focus: "Strength",
          exercises: [
            { name: "Wall Walk", targetSets: 4, targetReps: "3-4" },
            { name: "Headstand Push-Up Negative", targetSets: 4, targetReps: "4-6" },
            { name: "Pike Push-Up", targetSets: 4, targetReps: "8-10" },
            { name: "Handstand Shoulder Tap (wall)", targetSets: 3, targetReps: "10-12" },
          ],
        },
      },
      {
        id: "invert-handstand-balance",
        name: "Handstand Balance",
        tier: 2,
        xp: 120,
        badgeIcon: Target,
        focus: "Freestanding skill",
        description: "Kick-ups, heel pulls, and tuck holds for straight-line control.",
        reward: "Unlock heavy pressing nodes",
        targetSessions: 4,
        prerequisites: ["invert-headstand"],
        exerciseKeywords: ["handstand hold", "handstand balance"],
        template: {
          slug: "tree-handstand-balance",
          name: "Tree • Handstand Balance Flow",
          description: "Kick-up practice, heel pulls, and tuck holds to own the line.",
          category: "Inversion",
          difficulty: "intermediate",
          estimatedDuration: 36,
          focus: "Skill",
          exercises: [
            { name: "Handstand Wall Heel Pull", targetSets: 4, targetReps: "25s", targetType: "time" },
            { name: "Freestanding Handstand Hold", targetSets: 5, targetReps: "15-25s", targetType: "time" },
            { name: "Handstand Toe Taps", targetSets: 4, targetReps: "8-10" },
            { name: "Pike Press Negative", targetSets: 3, targetReps: "3-5" },
          ],
        },
      },
      {
        id: "invert-hspu",
        name: "Handstand Push Strength",
        tier: 3,
        xp: 150,
        badgeIcon: TrendingUp,
        focus: "Overhead pressing",
        description: "Deficit presses + shrugs build strict HSPU strength.",
        reward: "Unlock archer HSPU route",
        targetSessions: 4,
        prerequisites: ["invert-handstand-balance"],
        exerciseKeywords: ["handstand push-up"],
        template: {
          slug: "tree-handstand-push",
          name: "Tree • Handstand Push Force",
          description: "Deficit presses, wall facing reps, and partial one-arm holds.",
          category: "Inversion",
          difficulty: "intermediate",
          estimatedDuration: 38,
          focus: "Strength",
          exercises: [
            { name: "Wall-Facing Handstand Push-Up", targetSets: 5, targetReps: "5-7" },
            { name: "Deficit Handstand Push-Up", targetSets: 4, targetReps: "3-5" },
            { name: "Handstand Shrug", targetSets: 4, targetReps: "8-10" },
            { name: "One-Arm Handstand Support (wall)", targetSets: 4, targetReps: "20s", targetType: "time" },
          ],
        },
      },
      {
        id: "invert-archer-hspu",
        name: "Archer HSPU & OA Holds",
        tier: 4,
        xp: 210,
        badgeIcon: Trophy,
        focus: "Elite control",
        description: "Alt archer reps + one-arm holds for the endgame skill.",
        reward: "Unlock showcase + weighted runs",
        targetSessions: 5,
        prerequisites: ["invert-hspu"],
        exerciseKeywords: ["archer handstand push", "one arm handstand"],
        template: {
          slug: "tree-archer-hspu",
          name: "Tree • Archer Handstand Push Game",
          description: "Alternating archer presses, partial one-arm holds, and reactive balance drills.",
          category: "Inversion",
          difficulty: "advanced",
          estimatedDuration: 40,
          focus: "Skill",
          exercises: [
            { name: "One-Arm Handstand Shift (wall)", targetSets: 5, targetReps: "15s", targetType: "time" },
            { name: "Archer Handstand Push-Up", targetSets: 5, targetReps: "3-5" },
            { name: "HeS to HS Press", targetSets: 4, targetReps: "4-6" },
            { name: "Freestanding Handstand Push-Up", targetSets: 4, targetReps: "2-3" },
          ],
        },
      },
    ],
  },
  {
    id: "legs-tree",
    title: "Leg Precision Tree",
    subtitle: "Bulletproof knees en route to a clean pistol squat",
    icon: Mountain,
    accent: "from-green-500/10 via-emerald-500/5 to-lime-500/10",
    description: "Blend mobility + single-leg power until pistol squats feel smooth.",
    milestones: [
      {
        id: "legs-mobility",
        name: "Ankle & Hip Prep",
        tier: 0,
        xp: 50,
        badgeIcon: Footprints,
        focus: "Mobility",
        description: "Ankle rocks + cossacks open range for pistols.",
        reward: "Unlock shrimp squat path",
        targetSessions: 2,
        prerequisites: [],
        exerciseKeywords: ["cossack", "ankle"],
        template: {
          slug: "tree-leg-mobility",
          name: "Tree • Leg Mobility Primer",
          description: "Joint prep plus controlled cossack squats to open hips.",
          category: "Legs",
          difficulty: "beginner",
          estimatedDuration: 24,
          focus: "Mobility",
          exercises: [
            { name: "Ankle Rocks", targetSets: 3, targetReps: "15-20" },
            { name: "Elevated Cossack Squat", targetSets: 4, targetReps: "8-10 / side" },
            { name: "Assisted Pistol Box Tap", targetSets: 3, targetReps: "10 / side" },
          ],
        },
      },
      {
        id: "legs-shrimp",
        name: "Shrimp Squat Strength",
        tier: 1,
        xp: 80,
        badgeIcon: Activity,
        focus: "Unilateral strength",
        description: "Rear-foot work + shrimps beef up unilateral strength.",
        reward: "Unlock assisted pistols",
        targetSessions: 3,
        prerequisites: ["legs-mobility"],
        exerciseKeywords: ["shrimp squat"],
        template: {
          slug: "tree-shrimp-squat",
          name: "Tree • Shrimp Squat Builder",
          description: "Rear foot elevated work and tempo eccentrics to own the bottom.",
          category: "Legs",
          difficulty: "beginner",
          estimatedDuration: 30,
          focus: "Strength",
          exercises: [
            { name: "Rear-Foot Elevated Split Squat", targetSets: 4, targetReps: "8-10 / side" },
            { name: "Shrimp Squat", targetSets: 4, targetReps: "6-8 / side" },
            { name: "Assisted Pistol Squat", targetSets: 4, targetReps: "6-8 / side" },
            { name: "Nordic Hamstring Curl", targetSets: 3, targetReps: "5-8" },
          ],
        },
      },
      {
        id: "legs-negative",
        name: "Pistol Negatives",
        tier: 2,
        xp: 110,
        badgeIcon: Target,
        focus: "Control",
        description: "Slow negatives + box taps teach depth control.",
        reward: "Unlock full pistols node",
        targetSessions: 3,
        prerequisites: ["legs-shrimp"],
        exerciseKeywords: ["pistol negative"],
        template: {
          slug: "tree-pistol-negative",
          name: "Tree • Pistol Control Lab",
          description: "Slow tempos, pauses, and deficit balance drills.",
          category: "Legs",
          difficulty: "intermediate",
          estimatedDuration: 32,
          focus: "Control",
          exercises: [
            { name: "Pistol Squat Negative", targetSets: 5, targetReps: "3-5 / side" },
            { name: "Box Pistol Squat", targetSets: 4, targetReps: "6-8 / side" },
            { name: "Skater Squat", targetSets: 4, targetReps: "8-10 / side" },
            { name: "Single-Leg Romanian Deadlift", targetSets: 4, targetReps: "10-12 / side" },
          ],
        },
      },
      {
        id: "legs-pistol",
        name: "Full Pistol Squat",
        tier: 3,
        xp: 160,
        badgeIcon: Trophy,
        focus: "Skill execution",
        description: "Full-range pistols with pauses + core finishers.",
        reward: "Unlock weighted/explosive pistols",
        targetSessions: 4,
        prerequisites: ["legs-negative"],
        exerciseKeywords: ["pistol squat"],
        template: {
          slug: "tree-pistol-squat",
          name: "Tree • Clean Pistols",
          description: "Full range pistols, pause reps, and core stabilizers.",
          category: "Legs",
          difficulty: "advanced",
          estimatedDuration: 34,
          focus: "Skill",
          exercises: [
            { name: "Pistol Squat", targetSets: 5, targetReps: "4-6 / side" },
            { name: "Weighted Pistol Squat", targetSets: 4, targetReps: "3-5 / side" },
            { name: "Cossack Squat", targetSets: 4, targetReps: "8 / side" },
            { name: "Hanging Knee Raise", targetSets: 3, targetReps: "12-15" },
          ],
        },
      },
    ],
  },
]
