name: Setup Check

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  check-secrets:
    name: Check Required Secrets
    runs-on: ubuntu-latest
    
    steps:
      - name: Check DockerHub Username
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          if [ -z "$DOCKERHUB_USERNAME" ]; then
            echo "❌ DOCKERHUB_USERNAME secret is not set"
            echo "Please add your DockerHub username to GitHub repository secrets"
            exit 1
          else
            echo "✅ DOCKERHUB_USERNAME is configured"
          fi

      - name: Check DockerHub Token
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          if [ -z "$DOCKERHUB_TOKEN" ]; then
            echo "❌ DOCKERHUB_TOKEN secret is not set"
            echo "Please add your DockerHub access token to GitHub repository secrets"
            exit 1
          else
            echo "✅ DOCKERHUB_TOKEN is configured"
          fi

      - name: Check NextAuth Secret
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        run: |
          if [ -z "$NEXTAUTH_SECRET" ]; then
            echo "⚠️ NEXTAUTH_SECRET secret is not set"
            echo "Consider adding your NextAuth secret for production builds"
          else
            echo "✅ NEXTAUTH_SECRET is configured"
          fi

      - name: Check Database URL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          if [ -z "$DATABASE_URL" ]; then
            echo "⚠️ DATABASE_URL secret is not set"
            echo "This is required for Prisma builds. Add your database connection string."
            echo "For CI builds, you can use a dummy URL like:"
            echo "postgresql://user:password@localhost:5432/dbname?schema=public"
          else
            echo "✅ DATABASE_URL is configured"
          fi

      - name: Setup Complete
        run: |
          echo "🎉 Repository setup check complete!"
          echo "Your CI/CD pipeline should work correctly now."
